### ISSUE TITLE
Also sync drag movement

### ISSUE THREAD

**Issue by generator85** [metafizzy/flickity-as-nav-for#4]
I'm using the asNavFor function in Flickity to create a placeholder gallery underneath the main gallery. This works pretty well, but when you drag the gallery the movements aren't synced realtime (only when you let go).

Is it possible to mimic the exact movements of the main gallery?

**Comment by desandro** [comment]
Thank you for this feature request! Currently, no, there's no good way to mimic drag position across Flickity galleries. This may be an interesting feature, but I haven't heard any other interest in it yet.

**Comment by nikosolihin** [comment]
@generator85 check this out https://www.npmjs.com/package/flickity-mimic

Demo - https://hydnhntr.github.io/flickity-mimic/

**Comment by MattPurland** [comment]
@nikosolihin You've just made me incredibly happy (and relieved) - thanks for pointing this out!

**Comment by generator85** [comment]
Cool thanks!
