### ISSUE TITLE
Flickity asNavFor-carousel run 1 behind main-carousel

### ISSUE THREAD

**Issue by NicolasVanhecke** [metafizzy/flickity-as-nav-for#5]
### Is there an option to set the asNavFor-carousel run 1 slide behind te main-carousel?  
I want to accomplish something like this: [see my gif](http://g.recordit.co/3HJctJHxLx.gif). Only here the slides show image 1 and 1, I want it to show 1 and 2 (then 2 and 3) ... 
  
In the image there is **visually** only 1 slider. (In code: the big image is the `main-carousel` and the small image is the `asNavFor`) But If there is a feature to set the AsNavFor 1 behind the main slider I can make it feel like the small image is the next slide in the carousel. 

(I hope this makes sense, this is my [stackoverflow](http://stackoverflow.com/questions/44050042/flickity-slider-with-custom-css-per-carousel-cell/44051307))

**Comment by NicolasVanhecke** [comment]
I have tried initialIndex on one of them to set them 1 slide apart, but they are linked so I have no clue how to tackle this problem.

**Comment by desandro** [comment]
[flickity-mimic](https://github.com/hydnhntr/flickity-mimic) may be just the thing you're looking for

**Comment by NicolasVanhecke** [comment]
@desandro Yess! That is perfect for exactly what I wanted to accomplish! Thank you.

EDIT: might also be nice to include this directly in flickity or maybe set u a CDN or something.
